sudo: false
cache: yarn
language: node_js
env:
  global:
  - NODE_ENV='test'
  - secure: B0siTv85oBhwVqbbw17I/bKd1E8v7U7SzcvMgSLhYQpF3Yje95FoaDt0e3dVh8jy8i3nBChi0LiNnEwDTEEGtyABC2ZgZI2270tU06/JQ1m0IrwWIl3/FUotTVF6Rpqwym4YLrbeVr5Crt0+gzQEF+bsw47YKxuO+Kb4jG/STpHFg/fpeOMpEnlHD3qIx1PfeCVvXzyPoFC2mQcW6Xb1uVGQqpRcXTkIqWU8vBdEVJ5A1wUAEx9jxgZGKjswkiOuiSwBUJezIS4sGNoeHxAa7bq7uY0Zx2pARMsprXgrz/MG6oebAgbui4HhiJwLKSho1LVfISV8XM2LVGQ5QQXZTJoEi4fF4TX2nYG17XYbm7kaEPiwEtAmAp/P87H1T6iMiAOGR1WT8Za9mP1Jh0A+KpuTKPUUYapofz0dgzb6LWLOq/8Y50fevFZ0baDiqWIlhIJd9NAKppHGR5WPJVwlMNZfcQZpM//nWp1+B0fJn0UtoFJsC6/5uikQZ3K9D96GWbT4PagMPoQnlCZTU8jjC+tte8gqAECPj/Gl7sWCaML46MaLlsP6fHRiw4s3sCX98H0iMwUc2fUfjAabLeM+TVe1/soYf1grSMLhCd0AZwckEIirO9xJ34oSIVzJI1qdNaqQG0vkpPpqTgCzHZl6kSxpOFrxTDxTMHhpRZi3SA8=
  - secure: BpsMKK822PkiLnC7/aLh72POPFkE+BK0bL65RVJwtAkkz0Sg1E5dbC2BB2ddObwh87vNK/Cr1KFE/66mnec5wFLVusTRcN7aCB0qyMfHrS6Ww54X1LtTKIuF48TLBKhTM3Z90SSr40H6gzA0qEb1MZMSQdl0NQb/HUpq8d1Ny7m83o65AZx0PHmoO7K9FR2+Vf35i4+YWUUS36Jwz9bt2NGJgmwy/OhH6u2sRruwzOSuL17Ww3fjtVI6SCW//GOPiGZOEGNoKzVSbkmPpYk02i+JYW9ajHiY8o1D6FRBTFI400kC7ZNqhoCtC1zsZZEerK87Y6wmt7/afacn1Ft6fXlrr8h0dVXFWEstnxdida2rIpbYViEKj+APy0w/y6VNv0NbLQqjn3Eg5Hheiaux0eKOqlGuH9wQqZafymG8Vk07kbNmiTCy6nNNFV66ILgl5h3VhN4+QnDLtVNCXEf1G8Cet3x7jQCfYCXO52ChH4XHCZkcChy33SvU6PdHWDIZp7ngh1MUG2dFEqIwERAZVVp66oXQ2irFkd7wvXiymnY2iBPri4woyqMxXGRa/MxJ2OZTJPrlFiBKwwCbd6F9vgmd0dbS4Z6Z0vWClCwaunw8gNXIqA3sgOrsr8rBRc5/nXbtQAX7mcPCr9MiLzM+TBK5sSIxKR9jqjWGLvnUa6w=
  - secure: nfbSntEq9r0AQnsIZXPry14vV+XpaB7fYFLz5xSUJnE1IA2cMnr3Q83io8rYbEhe7e+msDId7FoCAlEEemmQvv2oTXdPseQ9jH4mSYKQhZHuFo37JvT8b1oJBaDnZAaqfmcFgyOElusFd2sA1x43XwRNrJFMCjFjSkclxfJh4KqONblnAxs7/PJ8e15X9jVBiLzt9VH1n/FBSbwya7x62MoZ7KJ5Dmmyj55xaj352glef73r5wfhYTWuS5UZwoqXDhVVm/wR+eucyZaDGW+Ad7HRolBVfjhSwkaprOY9esPhSXwCeNQyRXMIONDgTbo9QWnPwWU9ImQwRGKZrqOX0CeBi8WezHahLSCERYEsDX+QtjaITMAubObmZmvL8Mp5bdDmPo6WcA90N1GHpeCg56iBtBMUPIv1ao3e6bQ/B++raitUtYSHxijxB5krs211TpYxT8idSz8b5cDobkMrqs+wdvk6ROZoSyc+TCjcuXqEHJIJrwTFwyoYmj7UKJsPUah5KCRjzUz1WXUehYoyhriyqYUvph/b1084Kq4mCYd1FOP5Qpmr/hphn3nm53I8rjlFFSyS4ldKVqTBkQk1W7kCyj9WMMAII/wnjrfW8/8zJiSNTA3uFkwMJpocMKorazkKXylaK2xX9kqua/E7Hoalv6CfwcYlewdvbTwmnkk=
  - secure: T80ATNM9Q3qzv+SejLNyM3tanOTnE5D5y9/5zO1Ua6z/KSHk0JcegyNajGw0iNajmHcXe3WesRJrKCchb7bqwgxBS6QjDwW6Puq/G3TmYhMmGY510zDDl5jP65ie4JeRdOSwKnHQiWww50u01aiLrW9hNDiW7Cxm2v8/AfztDKOL7eoad8O1LEJHPg0+D9e7fssXeezCPV/slAYVlhGxglnjH6XO+Aaoqd/lZfi4IIpCRBLKxSoB7SPEg0PYdw5QvnOxP/s0gI1OoMm6BhpyveFbFuob6MUAVHX9IHOYYlzZKN5OZvNk1hBrozn62RNQfqwh5O9Se0lxblWkVYiTnFawiLdrBE6gQ7wy8hax5cRx+4TcL3fpjiA0SiK+TNDe5f1+5s8d37l0XjmL9cyeD59sMYRp1iI/fSb7aVAishaGbv6w3INEbenmxsJUrZ3g375iDQ086fuEmWaMW89SDhHOxWTnLJHrqF2EDR9LDDMGzTyTIiz7CzNUHNQ1xjTyAw+Fl3o4p4VPEYdZ91JSqpQHO0GTv/GAHB3RdWgIwCJtYmwaD+zvSbIBVmvVzUlPmKOl1dgNunsJtP7tZjQIMlZn+p4AEXQ/riS2KJUjLfx9YwLRkGj40S6eXiHVTG9oXsH6Iz8K8TTq5qSVo/+OSDAYiDMmIA3IvCZv9fnO8B0=
  - secure: W4e4nmNjYOL0p1ZN1TqwY0+rL93FWl+8BTZIImUgJ9Qzf2sybXLqgYzmsU5G+BWW8X5dDvvUDEacXo31Wync+SukODOZsR2SdlH4+KmxU2aVWB2AO/IVHPDsL8C1BHWHTUqNkdx2dh1WjxteIg8jv/AqHN5GFMa6o6BlN8OiVxYWTk9EYewdljg+aEdt/T06uB8mKtOQpOMhKoQ6HGi+J/qrTGWJb92SxmDlc83j8lfYL89TAJkWBI8JX6H7S2ZE7WnU6VhE6EKzfJ9CEJynYWnmg0PzE3NwAR1LC+sTTcq272WObYr68ITZHEL8QUTbpaL3r8mC5JsHP1qJGabB++3Lq+vcFoTtll5gU9Fa5J8ZpcG2Yha6buMv2szQ0cwo/TNK2nYnqqMm7TXijJnvrjVIkaZpDvn3v+tNO5PKZ9kJrCpDEhCIGoXkz5za/g7oKpwRILVQelZTy/YJgKn/2UzVkuLuhNoDHCRaBcFfgEV1In+6Ef4Q9Tpdc3Q3jJmdXlDbPt0hy2nhp+8/FgcyFE/5lE2qbFRakAurdFbWNlAV9DXNB5/arhaFllsKZqhLcO7v1uWTtzuxOrWVxPQhHtGY4YC3PjbKNNnOKozgC+so6yK60Gq/gdPQyIQtrg6md0awWzhyM3r6xZ2ibjdI15ZzvBy9hfeqIByetFj3BW4=
before_install:
- cd ./$SERVICE
- nvm install
- nvm use
- npm install --only=production
before_script:
- SERVICE=$SERVICE make ensure-dependencies
- sleep 10
script:
- make brand
- make package
- make qa
- make archive
- make check
matrix:
  include:
  - env: SERVICE=recipes-api
    services:
    - docker
  - env: SERVICE=recipes-crawler
    services:
    - docker
  - env: SERVICE=recipes-id-generator
    services:
    - docker
notifications:
  slack:
    secure: BhnELxm5ueZdM3XguL5JYAuZJaobyygZkx2kGpmmUv7fQfGCEX51BzSXo0qOa1B+zbDJGbwfK0AMYYC2c3WEyNQ9qQy04OzsD8h8qLZACZu4aDmbrMoeftWxFCozodWzKe5ZSWCfWJ22f7IiBev281vI3/g8pM90SFa/JmdUrCZ6MjkRdEeEf+cjxfpjagxteozWEsban/SA+vy8AfiWEt0+w2JXVE4yWo/7zW4xWIm0lQBAfWFJsQFVphl3riumPjDZQ3p7vzhrL0O7T61/FMvpTxrgGiwYMe8ipauFqRLZ9ZZGHZ8+daUEef6DenwNyX0R4vxXTPRHvjejFzo1/bHmu8x5/ykNdldOxNAr0IILpKJtrNFko9Z5bGKR1fnhDm0izzxSO7RKmXIiDnltv/RCm2U9P1NxWto0bydUNeInSQPKPuGH5D36gN902UjdwXWg/0QeV3r9YKeyqz0OwSgRb8iQP9iZo2XCSIB4oGT56l2wACPLo8zr8kO5vyc982G7/rFOVC2OkDYOViPY95CsRd6C1HvsddFjkWTNe6VhZeEVimbSIB4rMOPuvYVywljwrLbSUibP9IDVMhNXb7BVeuYPysUx9Epe7GHwguIoaX9/zaM+7Xeb2cxbUHNkUjbtjIIwhgvzmDSLmLFLCS7e4uUoBbc2Gas7WQfh1dM=
