sudo: false
cache: yarn
language: node_js
env:
  global:
  - NODE_ENV='test'
  # DOCKER_USERNAME
  - secure: hnjhn1EoTzu/B72kMakHlzQIrAERbV6IcDtDJWTnGLxXeFwK/Dtyurqrvuc/dTzWff37Gss+VtMEk1i+jTtDdTYpYUpAuiBNY9bTjGuRTS3oyehrbOrmh7iQDZXf+HB8/Xf6r1WQ+j/Be8sdat6aFgmacIjHvS10ABPFWm77YQuOvpC66LU8Vt5PTmW4k/BWtWWcZSTQPLLd7kVkSEih+b3nhgW+JMiwwsbcTni6y3DTcW37NVqkaz0blZgMQTgK1TLK3DvZ+7MS3rvKaDysiV++kOkoLLiYMDs5aKQWPEmxmdXT8Ry4fpRGZ37Cv0zDlrP8EO54Cc14cDHEJenwGqjxorCrdWYpzQvzg5V1zUnSZRHpO+VPFHidPijvu/TieL1McsBJlOFh0ciI7nCGE5rg7f5F2rFCOUtnmbAmZdm7Nb/g1mTW22YGvMLq33Lv341luwyMY/cmsQoR4ewBwW/nRmp4c4NpteciO3Vk/JwcqrK2WGMF4rJAYATS1xi0oz5D0Swhn1luwYFsjbnpT0H2w0PFXgXSzWMyQg949EAmUPsCB9LQC5Vn11mFnceVRCa1QiI0q42yg0og3k0ZxqPtnB8JVuwxUX3Gog89s4DVc6WshyQiEWgclZbQxbt78PFCDSXnVpUiY7fl0+GDhjk6MLlQnYhRFSHkJJZ0/1Y=
  # DOCKER_PASSWORD
  - secure: dY8jGLJayMC05Nw8RgMbxKf0FCCd1T/qh48sUxvT1Uwi1IfraYQP9FQgXIWAUGrU+n1I7K7TaUWgXikaQpKEebQLgtSSkdIchWp6V191cbEOfPIbzSJ6lDcPgHgWRk/LNJ29MoaqSqshnLPxfhE5vw9Jf9gs+hukUKYogUczEG6N+M7uaydDd9m76pgm7SailmJyqthIkxiJtzDz+E0BLMXbfnrjfnNRedYE5If2ZhCWEUulhAi3pMdA4NxW0uul4drOqZuZlfBqW5jQzfQKao3dj9oHFzKalgAukUIoSd1TkQMcOqvEPVhx13/EU8gkB0H4TDyAlUEUkLs2BewBEDpikf6posJkxA8lUbM4L1nIh19vFfLw75ZrfOEUvDwfKJGbkziBVQnBnlgCNAUxVwPPDOLoXPa5ZOHsMQcmaNoJ6leglg/i91OksTcD8tQFpNN0lFPd2phP8KVNbHAp8Yd4zqHANZPN+7lXYJeFmSrZJ41eh+SMIN+QQwTLMzZy+056ROp8bqBizpykv0+WPkhmzXy2ExAOMvb7puQ0cZur+uJ7niggc0h8rOdt9CjH8BOzG4tNcHgs1t0ziotYDGFHVAd6E6+3+UfWyCkVovPb1C+5Gmp1/OrYUmFTsY+YZ/RJIvdkwe37qDr3Df1RJPEFqsTvkakif9JzRyc4v14=
branches:
  only:
  - master
before_install:
- cd ./$SERVICE
- nvm install
- nvm use
- node --version
- SERVICE=$SERVICE make ensure-dependencies
script:
- make qa
- TRAVIS_BUILD_ID=$TRAVIS_BUILD_ID TRAVIS_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER make brand
- DOCKER_USERNAME=$DOCKER_USERNAME DOCKER_PASSWORD=$DOCKER_PASSWORD make build
matrix:
  include:
  - env: SERVICE=recipes-api
    services:
    - docker
  - env: SERVICE=recipes-crawler
    services:
    - docker
