sudo: false

cache: yarn

language: node_js

env:
  global:
  - NODE_ENV='test'
  - DOCKER_USERNAME='amgut'
  - DOCKER_PASSWORD='quayquay'

before_install:
  - cd ./$SERVICE
  - nvm install
  - nvm use
  - node --version

install: 
  - yarn install

before_script:
  - SERVICE=$SERVICE make ensure-dependencies
  - sleep 10

script:
  - make qa
  - make brand
  - DOCKER_USERNAME=$DOCKER_USERNAME DOCKER_PASSWORD=$DOCKER_PASSWORD make build
  - DOCKER_USERNAME=$DOCKER_USERNAME DOCKER_PASSWORD=$DOCKER_PASSWORD SERVICE=$SERVICE TRAVIS_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER make build

matrix:
  include:
    - env: SERVICE=recipes-api
      services:
        - docker
    - env: SERVICE=recipes-crawler
      services:
        - docker
    - env: SERVICE=recipes-id-generator
      services:
        - docker