sudo: false

cache: yarn

language: node_js

env:
  global:
  - NODE_ENV='test'
  - DOCKER_USERNAME='amgut+github'
  - DOCKER_PASSWORD='VT0EP118DEXRAEJSZDVAY0ZCLVRK4314QAPWJ5VUTZ30OTNNCO8KUUIM942AG2S3'

before_install:
  - cd ./$SERVICE
  - nvm install
  - nvm use
  - node --version

install: 
  - yarn install

before_script:
  - SERVICE=$SERVICE make ensure-dependencies
  - sleep 10

script:
  - make qa
  - make brand
  - SERVICE=$SERVICE TRAVIS_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER make package

matrix:
  include:
    - env: SERVICE=recipes-api
      services:
        - docker
    - env: SERVICE=recipes-crawler
      services:
        - docker
    - env: SERVICE=recipes-id-generator
      services:
        - docker