sudo: false
language: node_js
env:
  global:
  # DOCKER_USERNAME
  - secure: hnjhn1EoTzu/B72kMakHlzQIrAERbV6IcDtDJWTnGLxXeFwK/Dtyurqrvuc/dTzWff37Gss+VtMEk1i+jTtDdTYpYUpAuiBNY9bTjGuRTS3oyehrbOrmh7iQDZXf+HB8/Xf6r1WQ+j/Be8sdat6aFgmacIjHvS10ABPFWm77YQuOvpC66LU8Vt5PTmW4k/BWtWWcZSTQPLLd7kVkSEih+b3nhgW+JMiwwsbcTni6y3DTcW37NVqkaz0blZgMQTgK1TLK3DvZ+7MS3rvKaDysiV++kOkoLLiYMDs5aKQWPEmxmdXT8Ry4fpRGZ37Cv0zDlrP8EO54Cc14cDHEJenwGqjxorCrdWYpzQvzg5V1zUnSZRHpO+VPFHidPijvu/TieL1McsBJlOFh0ciI7nCGE5rg7f5F2rFCOUtnmbAmZdm7Nb/g1mTW22YGvMLq33Lv341luwyMY/cmsQoR4ewBwW/nRmp4c4NpteciO3Vk/JwcqrK2WGMF4rJAYATS1xi0oz5D0Swhn1luwYFsjbnpT0H2w0PFXgXSzWMyQg949EAmUPsCB9LQC5Vn11mFnceVRCa1QiI0q42yg0og3k0ZxqPtnB8JVuwxUX3Gog89s4DVc6WshyQiEWgclZbQxbt78PFCDSXnVpUiY7fl0+GDhjk6MLlQnYhRFSHkJJZ0/1Y=
  # DOCKER_PASSWORD
  - secure: dY8jGLJayMC05Nw8RgMbxKf0FCCd1T/qh48sUxvT1Uwi1IfraYQP9FQgXIWAUGrU+n1I7K7TaUWgXikaQpKEebQLgtSSkdIchWp6V191cbEOfPIbzSJ6lDcPgHgWRk/LNJ29MoaqSqshnLPxfhE5vw9Jf9gs+hukUKYogUczEG6N+M7uaydDd9m76pgm7SailmJyqthIkxiJtzDz+E0BLMXbfnrjfnNRedYE5If2ZhCWEUulhAi3pMdA4NxW0uul4drOqZuZlfBqW5jQzfQKao3dj9oHFzKalgAukUIoSd1TkQMcOqvEPVhx13/EU8gkB0H4TDyAlUEUkLs2BewBEDpikf6posJkxA8lUbM4L1nIh19vFfLw75ZrfOEUvDwfKJGbkziBVQnBnlgCNAUxVwPPDOLoXPa5ZOHsMQcmaNoJ6leglg/i91OksTcD8tQFpNN0lFPd2phP8KVNbHAp8Yd4zqHANZPN+7lXYJeFmSrZJ41eh+SMIN+QQwTLMzZy+056ROp8bqBizpykv0+WPkhmzXy2ExAOMvb7puQ0cZur+uJ7niggc0h8rOdt9CjH8BOzG4tNcHgs1t0ziotYDGFHVAd6E6+3+UfWyCkVovPb1C+5Gmp1/OrYUmFTsY+YZ/RJIvdkwe37qDr3Df1RJPEFqsTvkakif9JzRyc4v14=
  # F2F_KEY (https://food2fork.com/about/api)
  - secure: NWOOfmeaia2X8NPRxA/QM3WowYVhsnjltqYpcRPrHqPiyRP1GSqezm38G0Hs6wMwYgCZ/SOmT/0iv/1ILrQTgt8rWg930NanJ9Bki1Gh66onmHUg3OvvFCOSlBmreYih3zJUa7+QwZyUDVsxjaJ54frINgILM7wx4fFPyIoYgS4panT2wLe1XLnQvQGlZS/0UfcGD90s2H0BI5JFFXoyIBRTFMrlqtD2lSqmcthg3zsvTTSyW3Y2ny4RAGdR0O1rD8w8qfrMBY5byfSyQN63a/jrUKAwvu5xASN8ROS4pnYL4SSzx8fX2uHzIWGerUQ7IkMv+95hm8ZD8I0odYEZ678uAdL/QXwOuc1ZnzWOwrXaDzFt9M//r4zrpkXKx1SArvCViSq+XSN6674JKRmLZAUdUWgmHbowZqC/MIay2NbDBXrHnCDAN1mdhkyjAARPRYZ8grBQBVdvitrq8zOYDO77jRpUQT4er4GkxW5d2TkfGteahMS7ex5ctl+Jek0tdkS0Ze6ahr4LpNvJE28bNSBi2rEFn/osNbHvkCLK/fJt6Q1bnUCax8BQsqBtuTMvod+LkSjMomeP2vuFpgy83ZVhz0rM6MIJbpypiifZ1HLwn6aTME7xp6TdkQwE4EnUHGGMTB65BMm4XOY/r58gufoPgrDpB2bgDWhYqR/cSbk=
branches:
  only:
  - master
install: true
before_script:
- cd ./$SERVICE
- nvm install
- nvm use
- node --version
- SERVICE=$SERVICE make ensure-dependencies
script:
- TRAVIS_BUILD_ID=$TRAVIS_BUILD_ID TRAVIS_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER make brand
- SERVICE=$SERVICE TRAVIS_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER make package
- SERVICE=$SERVICE TRAVIS_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER make qa
- SERVICE=$SERVICE TRAVIS_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER DOCKER_USERNAME=$DOCKER_USERNAME DOCKER_PASSWORD=$DOCKER_PASSWORD F2F_KEY=$F2F_KEY make archive
- make check
matrix:
  include:
  - env: SERVICE=recipes-api
    services:
    - docker
  - env: SERVICE=recipes-crawler
    services:
    - docker
notifications:
  slack:
    secure: eJtVJ7Kj2e3vjJazLAayQ7in1zgY/7/+yWd0lPckymkEQFbbgpN8AGWCNePG+9AWMjzb7icQ7tHGi8ZBxCEd6cJp6bTBgBMRZjBagMzfMwmej193Sg0GGvg2DVKjTzDY3x0btU+h0K23raAFc6UIpYqm84CiD7RhGh5GRDbXSpynhD9GWuGkZWj3eezr/ZIzfRAeV63y/2mE8e0Sx29rS367ktW/0mN65J1AlcDtsMiwlHVNX9CQh6FQBOK4o3BbmTvjpz8Gz5mpBKdq5JBhoSAI+/QRK9+Vy3oA/cpdJoMT96nxuvJIVqNOw24JxrBK+mp8V6xvk31oOOsJeQCqysiRTNImujCJ26xgsty/HDeLIA2AyCNqEqkSZhbYHpBXwjenbrperRl3twiAGpnbYBrE4lBHi1dGNYtde4c5q2fac/t9Q3fsNGua92ryRvlJhs+jU7Cvgebg3x2FjJ0fzmLOHkXDdhMETPYFVBspMhBw7gSN3CQhO10gGEoh7CqwZuL7xTLsnj9745bfbISHdiTph4fo442XG9Vs6eUJ9fp/HZ/J9jU2OB0LOmx1Ei1yCBhTR8agDAqQGXwCnTxXxhBJo0lF4t5dOV3eIvEL2pwnNbw+vCYWaV6FZrNEcIG6/2FnTTnmwvTuDmbf3njTi72Omaikn9upptciOPKEDyg=
